services:
  db:
    build: .
    container_name: user-service-db
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_service_db:/var/lib/postgresql/data

volumes:
  user_service_db:
